
random_state: 101

verbose: True

dataset:
  training_data_path: './dataset/training_data.csv'
  test_data_path: './dataset/test_data.csv'
  validation_size: 0.33

model:
  decision_tree:
    criterion: 'entropy'

  random_forest:
    n_estimators: 10

  gradient_boost:
    n_estimators: 150
    criterion: 'friedman_mse'

model_save_path: './saved_model/'